{{- range $subnet := .Values.subnets }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-{{ lower $subnet.id }}
  namespace: default
spec:
  config: '{ 
    "cniVersion": "0.3.1",
    "name": "multus-{{ lower $subnet.id }}",
    "plugins": [
                { 
                    "name": "multus-{{ lower $subnet.id }}",
                    "type": "macvlan", 
                    "master": "vlan.{{ $subnet.vlanId }}", 
                    "mode": "bridge", 
                    "isDefaultGateway":false,
                    "forceAddress": false, 
                    "ipMasq": false,
                    "hairpinMode": false, 
                    "ipam": {
                      "type": "static",
                      "subnet": "2001:48d0:6020:{{ $subnet.id }}::0/64",
                      "rangeStart": "2001:48d0:6020:{{ $subnet.id }}:0000:0000:0000:0004",
                      "rangeEnd":   "2001:48d0:6020:{{ $subnet.id }}:ffff:ffff:ffff:ffff",
                      "gateway": "2001:48d0:6020:{{ $subnet.id }}::1",
                      "routes": [{
                                  "dst": "::/0",
                                  "gw": "2001:48d0:6020:{{ $subnet.id }}::1"
                                }] 
                    } 
                }, 
                { 
                  "type": "tuning",
                  "sysctl": {
                              "net.ipv6.conf.net1.autoconf": "0",
                              "net.ipv6.conf.net1.accept_ra": "0", 
                              "net.ipv6.conf.eth0.disable_ipv6": "1"
                            } 
                } 
              ] 
  }'
---
{{- end }}
