{{- $myConfigMap := lookup "v1" "ConfigMap" .Release.Namespace "xroot-scitokens" -}}
{{- if not $myConfigMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ $.Values.namespace }} 
  name: xroot-scitokens
data:
  scitokens.cfg: |
    [Global]
    onmissing = passthrough
    audience = https://wlcg.cern.ch/jwt/v1/any,redir.t2.ucsd.edu
    
    [Issuer CMS]
    issuer = https://cms-auth.cern.ch/
    base_path = /
    map_subject = False
    default_user = cmswriter
{{- end }}

